name: xxf_resources
description: "资源文件与国际化"
version: 0.0.1
homepage: "https://github.com/NBXXF/xxf_flutter"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #图片,字体,颜色生成清单,类似swiftGen,需要在dev_dependencies 配置这两行   build_runner: flutter_gen_runner:
  flutter_gen: ^5.10.0

  #国际化,idea 使用flutter intl插件自动生成清单文件
  #教程 https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization?utm_source=chatgpt.com
  flutter_localizations:
    sdk: flutter
  #messages_all.dart 会引入intl包
  intl: ^0.19.0

#配置idea插件flutter intl
flutter_intl:
  enabled: true
  arb_dir: lib/l10n       # ARB 文件所在的文件夹
  template_arbs: [intl_en.arb]  # 默认的 ARB 文件
  output_dir: lib/generated/l10n   # 生成的本地化 Dart 文件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 生成图片等资源文件
  build_runner:
  flutter_gen_runner:

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
