builders:
  xxf_codegen:
    import: "package:xxf_generator/xxf_generator.dart"
    builder_factories: []
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders:
      # 自定义的json_serializable
      - json_serializable
      # 自定义的auto_route_generator
      - auto_route_generator:auto_route_generator
      # 自定义的injectable_generator
      - injectable_generator:injectable_generator
      # 自定义的xxf_http_generator
      - xxf_http_generator
      # 自定义的xxf_cache_generator
      - xxf_cache_generator
      # 自定义的isar_generator
      - isar_generator
      # 自定义的flutter_gen_runner
      - flutter_gen_runner