name: xxf_generator
description: "A new Flutter xxf all codegen project."
version: 0.0.10+4
homepage: "https://github.com/NBXXF/xxf_flutter"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

#聚合各个插件生成库,xxf_generator 一键配置
dependencies:
  flutter:
    sdk: flutter
  build: ^2.0.0  # 添加这一行
  json_annotation: ^4.9.0
  #编译时库
  build_runner: ^2.4.15
  #json
  json_serializable: ^6.8.0
  #路由生成
  auto_route_generator: ^10.0.1
  # 依赖注入 配合get_it+injectable 生成代码
  injectable_generator: ^2.7.0
  #http 生成自己的
  xxf_http_generator: ^0.0.10+1
  #生成声明式kv存储
  xxf_cache_generator: ^0.0.10+2
  #xxf_cache 有isar 数据库
  isar_generator: ^3.1.0+1
  # 生成图片等资源文件
  flutter_gen_runner: ^5.10.0

dependency_overrides:
  source_gen: ^1.2.2
  analyzer: ^6.11.0
  dart_style: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
