name: xxf_arch
description: "A Routing and State Manager Flutter package project."
version: 0.0.9
homepage: "https://github.com/NBXXF/xxf_flutter"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #生命周期管理组件
  xxf_lifecycle:
  #资源文件生成与国际化
  xxf_resources:
  #流处理
  xxf_flow: ^0.0.3


  #自动注入路由框架,优于go_router+go_router_builder
  auto_route: ^10.0.1
  #依赖注入框架
  get_it: ^8.0.3
  injectable: ^2.5.0 #dev_dependencies需要配置 injectable_generator: ^2.7.0
  #状态管理器
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  flutter_hooks: ^0.21.2


  #屏幕适配
  flutter_screenutil: ^5.9.3
  #toast or loading
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #自动注入路由框架
  build_runner:
  auto_route_generator: ^10.0.1


flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
