name: xxf_http_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
homepage: "https://github.com/NBXXF/xxf_flutter"
repository: "https://github.com/NBXXF/xxf_flutter"
version: 0.0.10+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ^6.11.0
  build: ^2.4.1
  built_collection: ^5.1.1
  code_builder: ^4.10.0
  dart_style: '>=2.3.7 <4.0.0'

  dio: ^5.0.0
  protobuf: ^3.1.0
  source_gen: ^1.2.2
  retrofit: ^4.4.2
  xxf_http:

dev_dependencies:
  lints: any
  test: ^1.25.0
#dependency_overrides:
#  xxf_http:
#    path: ../xxf_http
